Repository Molara-Lab/Molara, pull requests merged in 2024-03, with the labels that each got.

#290 Add typing_extensions to pyproject.toml
  pyproject.toml
Labels: bug

#293 Change energy plot y-label unit to hartree
  src/molara/Gui/trajectory_dialog.py
Labels: bug, quickfix

#297 Add coverage report
  .github/workflows/test.yml
  README.md
Labels: enhancement, housekeeping

#301 Add .coord & _POSCAR suffix to example files
  examples/POSCAR/BN_POSCAR
  examples/POSCAR/BN_cartesian_POSCAR
  examples/POSCAR/Ba2YCu3O7_POSCAR
  examples/POSCAR/Mg3Sb2_POSCAR
  examples/POSCAR/SrTiO3_POSCAR
  examples/POSCAR/magnesium_antimonite_2
  examples/coord/coord1.coord
  examples/coord/coord2.coord
  examples/coord/coord3.coord
  tests/molara/Structure/test_crystal.py
Labels: bug, quickfix

#312 Create tests for Rendering, Shaders, Buffers, Exporter, MainWindow, MeasurementDialog
  .github/workflows/test.yml
  examples/xyz/ferrocene.xyz
  pyproject.toml
  pytest.ini
  src/molara/Gui/main_window.py
  src/molara/Gui/measuring_tool_dialog.py
  src/molara/Gui/structure_widget.py
  src/molara/Rendering/rendering.py
  tests/molara/Structure/io/test_exporter.py
  tests/molara/gui/__init__.py
  tests/molara/gui/test_main_window.py
  tests/molara/gui/test_measurement_dialog.py
  tests/molara/rendering/__init__.py
  tests/molara/rendering/test_buffers.py
  tests/molara/rendering/test_camera.py
  tests/molara/rendering/test_rendering.py
  tests/molara/rendering/test_shaders.py
  tests/molara/test_gui_and_rendering.py
Labels: housekeeping

#227 Add cython-lint
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  src/molara/Rendering/cylinder.pyx
  src/molara/Tools/mathtools.pyx
  src/molara/Tools/raycasting.pyx
Labels: enhancement, housekeeping

#322 Orthographic projection
  src/molara/Gui/builder.py
  src/molara/Gui/crystal_dialog.py
  src/molara/Gui/form.ui
  src/molara/Gui/main_window.py
  src/molara/Gui/structure_widget.py
  src/molara/Gui/trajectory_dialog.py
  src/molara/Gui/ui_form.py
  src/molara/Rendering/camera.py
  src/molara/Structure/molecules.py
  src/molara/Structure/structures.py
  tests/molara/Structure/test_molecules.py
  tests/molara/gui/test_main_window.py
  tests/molara/gui/test_measurement_dialog.py
  tests/molara/rendering/test_camera.py
Labels: enhancement, rendering

#328 Remove google pydocstyle filter from ruff
  cython_build.py
  pyproject.toml
  src/molara/Eval/aos.py
  src/molara/Gui/builder.py
  src/molara/Gui/crystal_dialog.py
  src/molara/Gui/main_window.py
  src/molara/Gui/measuring_tool_dialog.py
  src/molara/Gui/structure_widget.py
  src/molara/Gui/supercell_dialog.py
  src/molara/Gui/trajectory_dialog.py
  src/molara/Rendering/buffers.py
  src/molara/Rendering/camera.py
  src/molara/Rendering/rendering.py
  src/molara/Rendering/shaders.py
  src/molara/Structure/atom.py
  src/molara/Structure/basisset.py
  src/molara/Structure/crystal.py
  src/molara/Structure/crystals.py
  src/molara/Structure/drawer.py
  src/molara/Structure/io/exporter.py
  src/molara/Structure/io/importer.py
  src/molara/Structure/io/importer_crystal.py
  src/molara/Structure/molecule.py
  src/molara/Structure/molecules.py
  src/molara/Structure/mos.py
  src/molara/Structure/structure.py
  src/molara/Structure/structures.py
  tests/molara/Structure/io/test_exporter.py
  tests/molara/Structure/test_basisset.py
  tests/molara/gui/test_main_window.py
  tests/molara/gui/test_measurement_dialog.py
  tests/molara/rendering/test_buffers.py
  tests/molara/rendering/test_rendering.py
  tests/molara/rendering/test_shaders.py
  tests/molara/test_gui_and_rendering.py
Labels: housekeeping

#331 Use `uv` to install packages for testing workflow
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: housekeeping

#334 Limit version of PySide6 to 6.6.2 to prevent mypy from failing
  pyproject.toml
Labels: bug, housekeeping
