Repository Molara-Lab/Molara, pull requests merged in 2024-04, with the labels that each got.

#344 Fix case sensitivity when parsing .xyz files
  src/molara/Structure/io/importer.py
Labels: bug

#347 Create release workflow
  .github/workflows/release.yml
  .github/workflows/test.yml
  MANIFEST.in
  pyproject.toml
  setup.py
Labels: enhancement, housekeeping

#305 Increase coverage
  src/molara/Structure/crystal.py
  src/molara/Structure/io/importer_crystal.py
  src/molara/Structure/structure.py
  tests/molara/Structure/test_crystal.py
  tests/molara/Structure/test_molecule.py
Labels: housekeeping

#351 Feature/350 implement showing multiple structures at the same time
  src/molara/Gui/builder.py
  src/molara/Gui/crystal_dialog.py
  src/molara/Gui/main_window.py
  src/molara/Gui/structure_widget.py
  src/molara/Gui/trajectory.ui
  src/molara/Gui/trajectory_dialog.py
  src/molara/Gui/ui_trajectory.py
  src/molara/Rendering/shaders.py
  src/molara/Structure/molecules.py
  src/molara/__main__.py
  tests/molara/gui/test_main_window.py
  tests/molara/gui/test_measurement_dialog.py
  tests/molara/rendering/test_shaders.py
Labels: enhancement, rendering

#360 Feature/352 enable chosing between ball and stick and only stick
  .gitignore
  Molara.pyproject
  Settings/Structure/Default.json
  src/molara/Gui/form.ui
  src/molara/Gui/main_window.py
  src/molara/Gui/structure_customizer.ui
  src/molara/Gui/structure_customizer_dialog.py
  src/molara/Gui/structure_widget.py
  src/molara/Gui/ui_form.py
  src/molara/Gui/ui_structure_customizer.py
  src/molara/Structure/drawer.py
  tests/molara/Structure/test_drawer.py
  tests/molara/gui/test_main_window.py
  tests/molara/test_gui_and_rendering.py
Labels: enhancement, gui, rendering

#364 Simplified code for xyz file import
  src/molara/Structure/io/importer.py
Labels: housekeeping
