Repository Molara-Lab/Molara, pull requests merged in 2024-05, with the labels that each got.

#362 Add periodic table data and color scheme information
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  develop/colors/get_colors.py
  develop/periodic_table/get_pd_data.py
  pyproject.toml
  src/molara/Structure/atom.py
  src/molara/Structure/atom_colors.json
  src/molara/Structure/crystal.py
  src/molara/Structure/io/exporter.py
  src/molara/Structure/periodic_table.json
  src/molara/Structure/periodic_table_copyright
  tests/molara/Structure/test_atom.py
  tests/molara/Structure/test_crystal.py
Labels: enhancement

#376 Create .coderabbit.yaml to exlude ui_* files
  .coderabbit.yaml
Labels: housekeeping

#378 Fix xyz import
  src/molara/Structure/io/importer.py
  src/molara/Structure/molecule.py
Labels: bug

#370 Feature/335 implement atom number
  README.md
  Settings/Structure/Default.json
  src/molara/Gui/form.ui
  src/molara/Gui/structure_customizer.ui
  src/molara/Gui/structure_customizer_dialog.py
  src/molara/Gui/structure_widget.py
  src/molara/Gui/supercell_dialog.py
  src/molara/Gui/ui_form.py
  src/molara/Gui/ui_structure_customizer.py
  src/molara/Rendering/atom_labels.py
  src/molara/Rendering/buffers.py
  src/molara/Rendering/camera.py
  src/molara/Rendering/rendering.py
  src/molara/Rendering/shaders.py
  tests/molara/gui/test_main_window.py
  tests/molara/rendering/test_atom_labels.py
  tests/molara/rendering/test_buffers.py
  tests/molara/rendering/test_rendering.py
  tests/molara/rendering/test_shaders.py
Labels: enhancement, rendering

#395 Add color scheme to structure customiser
  Settings/Structure/Default.json
  src/molara/Gui/structure_customizer.ui
  src/molara/Gui/structure_customizer_dialog.py
  src/molara/Gui/ui_structure_customizer.py
  src/molara/Structure/atom.py
  src/molara/Structure/drawer.py
Labels: rendering

#399 Hotfix for win problem
  src/molara/Rendering/rendering.py
Labels: bug

#406 Add markdownlint to pre-commit
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
Labels: housekeeping

#405 Fix `matplotlib` error in new version
  pyproject.toml
  src/molara/Gui/trajectory_dialog.py
Labels: bug

#371 Enable python 3.12 support
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: enhancement, housekeeping

#393 Fix values cut off in measurement tool
  src/molara/Gui/measuring_tool.ui
  src/molara/Gui/measuring_tool_dialog.py
  src/molara/Gui/ui_measuring_tool.py
  tests/molara/gui/test_measurement_dialog.py
Labels: bug, enhancement
