Repository Molara-Lab/Molara, pull requests merged in 2024-08, with the labels that each got.

#441 First steps in cleaning up structure widget
  src/molara/Gui/structure_widget.py
  src/molara/Structure/crystal.py
  tests/molara/Structure/test_crystal.py
Labels: housekeeping

#440 Increase coverage of builder.py
  tests/molara/gui/test_builder.py
Labels: housekeeping

#443 Clean up structure_widget
  src/molara/Gui/main_window.py
  src/molara/Gui/structure_widget.py
  tests/molara/gui/test_main_window.py
  tests/molara/gui/test_structure_widget.py
  tests/molara/test_gui_and_rendering.py
Labels: housekeeping

#451 Fix deprecation warnings in Pytest
  src/molara/Gui/structure_widget.py
  tests/molara/gui/test_structure_widget.py
Labels: quickfix

#397 Add molara logo
  .pre-commit-config.yaml
  MANIFEST.in
  README.md
  img/MolaraLogo.png
  img/MolaraLogo.svg
  pyproject.toml
  src/molara/MolaraLogo.png
  src/molara/__main__.py
  tests/molara/test_main_program.py
Labels: enhancement

#464 Move settings folder to user path
  src/molara/Gui/structure_customizer_dialog.py
  tests/molara/gui/test_main_window.py
Labels: bug

#457 Bump `numpy` for build and add test for installing from `wheel`
  .github/workflows/test_wheel.yml
  pyproject.toml
  src/molara/Gui/structure_customizer_dialog.py
  src/molara/settings/structure/Default.json
  tests/molara/gui/test_main_window.py
Labels: enhancement

#473 Remove obsolete CrystalImporter class
  src/molara/structure/io/importer.py
Labels: quickfix
