Repository Molara-Lab/Molara, pull requests merged in 2024-10, with the labels that each got.

#482 Drop `python3.9` support
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  pyproject.toml
  src/molara/gui/builder.py
  src/molara/gui/measuring_tool_dialog.py
  src/molara/structure/crystal.py
  src/molara/structure/io/exporter.py
  src/molara/structure/io/importer.py
  src/molara/structure/io/importer_crystal.py
  src/molara/util/exceptions.py
  tests/molara/rendering/test_buffers.py
  tests/molara/structure/io/test_importer_crystal.py
  tests/molara/structure/test_drawer.py
  tests/molara/structure/test_molecule.py
  tests/molara/structure/test_molecules.py
Labels: housekeeping

#489 Use 1st party `uv` installation
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .github/workflows/test_wheel.yml
Labels: housekeeping

#509 Fix rotation
  src/molara/gui/structure_widget.py
Labels: bug

#502 Feature/207 visualize molecular orbitals
  .gitignore
  Molara.pyproject
  examples/molden/SPDFG_orbitals.molden
  examples/molden/benzene.molden
  examples/molden/h2o.molden
  examples/molden/o2.molden
  pyproject.toml
  setup.py
  src/molara/data/__init__.py
  src/molara/data/constants.py
  src/molara/eval/aos.pxd
  src/molara/eval/aos.py
  src/molara/eval/aos.pyx
  src/molara/eval/generate_voxel_grid.pyx
  src/molara/eval/marchingcubes.py
  src/molara/eval/mos.pxd
  src/molara/eval/mos.pyx
  src/molara/eval/populationanalysis.py
  src/molara/eval/trianglelookuptable.py
  src/molara/gui/form.ui
  src/molara/gui/main_window.py
  src/molara/gui/mos_dialog.py
  src/molara/gui/mos_dialog.ui
  src/molara/gui/structure_widget.py
  src/molara/gui/ui_form.py
  src/molara/gui/ui_mos_dialog.py
  src/molara/rendering/buffers.py
  src/molara/rendering/rendering.py
  src/molara/structure/atom.py
  src/molara/structure/basisset.py
  src/molara/structure/crystal.py
  src/molara/structure/io/importer.py
  src/molara/structure/molecularorbitals.py
  src/molara/structure/molecule.py
  src/molara/structure/mos.py
  src/molara/structure/structure.py
  tests/molara/eval/__init__.py
  tests/molara/eval/test_aos.py
  tests/molara/eval/test_mos.py
  tests/molara/eval/test_populationanalysis.py
  tests/molara/gui/test_mos_dialog.py
  tests/molara/structure/test_aos.py
  tests/molara/structure/test_atom.py
  tests/molara/structure/test_basisset.py
  tests/molara/structure/test_crystal.py
  tests/molara/structure/test_molecule.py
  tests/molara/structure/test_mos.py
  tests/molara/test_gui_and_rendering.py
Labels: enhancement, rendering

#514 Simplify rendering.py
  src/molara/rendering/rendering.py
Labels: housekeeping
