Repository Molara-Lab/Molara, pull requests merged in 2024-11, with the labels that each got.

#524 Fix PTH123 `open()` should be replaced by `Path.open()`
  develop/colors/get_colors.py
  develop/periodic_table/get_pd_data.py
  pyproject.toml
  src/molara/gui/structure_customizer_dialog.py
  src/molara/rendering/camera.py
  src/molara/structure/atom.py
  src/molara/structure/io/exporter.py
  src/molara/structure/io/importer.py
  src/molara/structure/io/importer_crystal.py
  src/molara/structure/periodic_table.json
  tests/molara/gui/test_main_window.py
  tests/molara/rendering/test_camera.py
  tests/molara/structure/io/test_exporter.py
  tests/molara/structure/io/test_importer.py
Labels: housekeeping

#532 Fix PLR6104
  src/molara/gui/builder.py
  src/molara/structure/basisset.py
  tests/molara/structure/test_aos.py
Labels: housekeeping

#512 Feature/speed up molecular orbitals
  examples/molden/caffeine.molden
  examples/molden/hf.molden
  pyproject.toml
  setup.py
  src/molara/eval/aos.pyx
  src/molara/eval/generate_voxel_grid.pyx
  src/molara/eval/marchingcubes.py
  src/molara/eval/marchingcubes.pyx
  src/molara/eval/mos.pxd
  src/molara/eval/mos.pyx
  src/molara/gui/mos_dialog.py
  src/molara/gui/mos_dialog.ui
  src/molara/gui/ui_mos_dialog.py
  src/molara/structure/io/importer.py
  src/molara/structure/molecularorbitals.py
  tests/molara/gui/test_customizer_dialog.py
  tests/molara/gui/test_mos_dialog.py
  tests/molara/test_gui_and_rendering.py
Labels: enhancement, calculations

#536 Fix bug where mos are not drawn by copying the renderer object
  src/molara/gui/export_image_dialog.py
  src/molara/gui/export_image_dialog.ui
  src/molara/gui/structure_widget.py
  src/molara/gui/ui_export_image_dialog.py
  src/molara/gui/virtual_rendering_window.py
  src/molara/gui/virtual_rendering_window.ui
  src/molara/rendering/camera.py
  src/molara/rendering/rendering.py
  src/molara/rendering/shaders.py
  tests/molara/gui/test_export_image_dialog.py
  tests/molara/rendering/test_camera.py
  tests/molara/rendering/test_shaders.py
Labels: bug
